name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install Dependencies
      run: npm install
    - name: Build stuff
      run: npm run build
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.1.2
      env:
        BUILD_DIR: public/
      with:
        GH_PAT: ${{ secrets.GH_PAT }}
